
services:
  my-cust:
    container_name: mycust
    # image: n8nio/n8n
    build:
      context: .
      dockerfile: Dockerfile   
    env_file:
      - .env
    # volumes:
    #   - ./output:/tmp/output
    #   - ./etl_sh:/app/etl_sh
    #   - ./src:/app/src
    # args:
    #     AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}    
    networks:
      - my-network
    restart: unless-stopped

networks:
  my-network:
    driver: bridge